### PR TITLE
Fix token occasionally having the wrong yaml type

### PR DESCRIPTION
**Pull request by Cynerva**
Fixes https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/619

Currently untested.

### CODE REVIEW

**Comment by hyperbolic2346** [comment]
LGTM

**Comment by ktsakalozos** [comment]
LGTM +1

The travis tests are failing because of the strict confinement of charm-tools

@Cynerva , consider changing the test-convoluted of the Makefile to something similar to this:
```
test-convoluted:
        /snap/bin/charm build -o ${HOME}/tmp -r --no-local-layers -l DEBUG
        tox -c ${HOME}/tmp/builds/etcd/tox.ini
        rm -rf ${HOME}/tmp
```

**Comment by Cynerva** [comment]
Fixed the Makefile for travis, looks like that worked, thanks @ktsakalozos 

Did a test deploy with the code in this branch, all good, ready to merge :+1:

**Comment by ktsakalozos** [comment]
Thanks!

**Pull request merged**
